info:
  contact: {}
  title: Social media api
paths:
  /helloworld:
    get:
      consumes:
      - application/json
      description: This end point for testing purpose
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Test hello world
      tags:
      - Publicly exposed
swagger: "2.0"
