info:
  contact: {}
  title: Tag service Api
paths:
  /:
    get:
      consumes:
      - application/json
      description: do nothing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: YOYO example
      tags:
      - example
swagger: "2.0"
